# This file is for Netlify-specific configurations.
# Since the build is handled by GitHub Actions, the [build] settings here
# are more for reference or if Netlify's build system were to be used directly.
# The GitHub Actions workflow specifies the build command and publish directory.

[build]
  # command = "pnpm run build" # This should match the build command for the platform package.json
  publish = ".next"          # Relative to the 'platform' directory where this netlify.toml resides

# Example: Redirects
# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"
#   status = 301

