name: Netlify Production Deployment (main)

on:
  push:
    branches:
      - main # Or your designated production branch

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    name: Build and Deploy to Production
    environment:
      name: production
      url: ${{ steps.deploy-netlify.outputs.NETLIFY_LIVE_URL }} # This will be set if you capture output
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Specify your Node.js version
          cache: 'npm' # or 'yarn'

      - name: Install dependencies
        run: npm ci # or yarn install --frozen-lockfile

      # Optional: Add linting step
      # - name: Lint code
      #   run: npm run lint # or yarn lint

      - name: Run tests
        run: npm test # or yarn test (ensure your test scripts are configured)

      - name: Build project
        run: npm run build # or yarn build

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify Production
        id: deploy_production
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          netlify deploy \
            --dir=.next \
            --prod \
            --message="Production Deploy: ${{ github.sha }} - ${{ github.event.head_commit.message }}" \
            --json > netlify_prod_deploy.json
          echo "NETLIFY_LIVE_URL=$(jq -r .deploy_url netlify_prod_deploy.json)" >> $GITHUB_ENV
          echo "Deployment to production complete. Live URL: $(jq -r .deploy_url netlify_prod_deploy.json)"

